Repository entando-k8s/entando-k8s-operator-common, pull requests merged in 2020-10, with the labels that each got.

#40 ENG-1266 made secret mounting more flexible
  jenkins-x.yml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/EntandoOperatorConfig.java
  src/main/java/org/entando/kubernetes/controller/EntandoOperatorConfigProperty.java
  src/main/java/org/entando/kubernetes/controller/ServiceDeploymentResult.java
  src/main/java/org/entando/kubernetes/controller/common/TlsHelper.java
  src/main/java/org/entando/kubernetes/controller/creators/DeploymentCreator.java
  src/main/java/org/entando/kubernetes/controller/creators/SecretCreator.java
  src/main/java/org/entando/kubernetes/controller/spi/DeployableContainer.java
  src/main/java/org/entando/kubernetes/controller/spi/SecretToMount.java
  src/test/java/org/entando/kubernetes/controller/common/examples/TestServerDeployableContainer.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployExampleServiceTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/AddExampleWithEmbeddedDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/KeycloakClientTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/support/EntandoAppIntegrationTestHelper.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/support/HttpTestHelper.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/support/TestFixturePreparation.java
  src/test/java/org/entando/kubernetes/controller/quarkus/DummyBean.java
Labels: approved, size/L

#41 Update OWNERS
  OWNERS
Labels: approved, size/XS

#42 ENG-872 and ENG-1330
  .idea/runConfigurations/Tags__inter_process__.xml
  pom.xml
  src/main/java/org/entando/kubernetes/client/DefaultPodClient.java
  src/main/java/org/entando/kubernetes/client/EntandoExecListener.java
  src/main/java/org/entando/kubernetes/controller/DeployCommand.java
  src/main/java/org/entando/kubernetes/controller/EntandoOperatorConfig.java
  src/main/java/org/entando/kubernetes/controller/EntandoOperatorConfigProperty.java
  src/main/java/org/entando/kubernetes/controller/ServiceDeploymentResult.java
  src/main/java/org/entando/kubernetes/controller/common/ConfigurableResourceCalculator.java
  src/main/java/org/entando/kubernetes/controller/common/ConfigurableStorageCalculator.java
  src/main/java/org/entando/kubernetes/controller/common/CreateExternalServiceCommand.java
  src/main/java/org/entando/kubernetes/controller/common/LimitAndRequestCalculator.java
  src/main/java/org/entando/kubernetes/controller/creators/DatabasePreparationPodCreator.java
  src/main/java/org/entando/kubernetes/controller/creators/DeploymentCreator.java
  src/main/java/org/entando/kubernetes/controller/creators/IngressCreator.java
  src/main/java/org/entando/kubernetes/controller/creators/PersistentVolumeClaimCreator.java
  src/main/java/org/entando/kubernetes/controller/creators/ServiceAccountCreator.java
  src/main/java/org/entando/kubernetes/controller/k8sclient/PodClient.java
  src/main/java/org/entando/kubernetes/controller/k8sclient/PodWaitingClient.java
  src/main/java/org/entando/kubernetes/controller/spi/ParameterizableContainer.java
  src/test/java/org/entando/kubernetes/controller/common/examples/MinimalKeycloakContainer.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ContainerUsingExternalDatabaseMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ContainerUsingExternalDatabaseTestBase.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ControllerExecutorMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ControllerExecutorMockServerTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ControllerExecutorTestBase.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/DefaultClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ImageResolutionTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/InProcessTestUtil.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/PublicIngressingMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/PublicIngressingMockServerTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/PublicIngressingTestBase.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/SpringBootContainerMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/SpringBootContainerTestBase.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/k8sclientdouble/PodClientDouble.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployExampleServiceOnExternalDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployExampleServiceTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/AddExampleWithEmbeddedDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/DeployContainerWithResourceLimitsRequestsTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/KeycloakClientTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/podwaiters/PodWaiterTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/support/KeycloakIntegrationTestHelper.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/support/PodResourceDouble.java
  src/test/java/org/entando/kubernetes/controller/test/support/assertionhelper/ResourceRequirementsAssertionHelper.java
  src/test/java/org/entando/kubernetes/controller/test/support/stubhelper/DeployableStubHelper.java
  src/test/java/org/entando/kubernetes/controller/unittest/ServiceDeploymentResultTest.java
  src/test/java/org/entando/kubernetes/controller/unittest/common/ConfigurableResourceCalculatorTest.java
  src/test/java/org/entando/kubernetes/controller/unittest/common/ConfigurableStorageCalculatorTest.java
  src/test/java/org/entando/kubernetes/controller/unittest/common/ResourceCalculatorTest.java
  src/test/java/org/entando/kubernetes/controller/unittest/common/StorageCalculatorTest.java
  src/test/java/org/entando/kubernetes/controller/unittest/creators/DeploymentCreatorTest.java
  src/test/java/org/entando/kubernetes/controller/unittest/creators/PersistentVolumeCreatorTest.java
  src/test/java/org/entando/kubernetes/controller/unittest/k8sclient/PodClientTest.java
Labels: size/XXL

#45 ENG-1329 adding view cluster role for KUBE_PING to work
  src/main/java/org/entando/kubernetes/controller/DeployCommand.java
  src/main/java/org/entando/kubernetes/controller/EntandoOperatorConfig.java
  src/main/java/org/entando/kubernetes/controller/creators/ServiceAccountCreator.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/BareBonesDeployableTestBase.java
Labels: approved, size/M
