Repository entando-k8s/entando-k8s-operator-common, pull requests merged in 2020-09, with the labels that each got.

#35 Eng 1205 new environment variables
  src/main/java/org/entando/kubernetes/controller/EntandoOperatorConfigProperty.java
Labels: approved, size/XS

#38 Eng 1205 no get secret access
  src/main/java/org/entando/kubernetes/controller/creators/KeycloakClientCreator.java
  src/main/java/org/entando/kubernetes/controller/creators/SecretCreator.java
Labels: approved, size/S

#39 ENG-703 keycloak clients web origins support
  src/main/java/org/entando/kubernetes/client/DefaultKeycloakClient.java
  src/main/java/org/entando/kubernetes/controller/KeycloakClientConfig.java
  src/main/java/org/entando/kubernetes/controller/creators/KeycloakClientCreator.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/KeycloakClientTest.java
  src/test/java/org/entando/kubernetes/controller/quarkus/DummyBean.java
Labels: approved, size/M
