Repository entando-k8s/entando-k8s-operator-common, pull requests merged in 2020-04, with the labels that each got.

#16 Eng 366 cleanup link created stuff
  .idea/codeStyles/Project.xml
  config/owasp-dependency-check-suppression.xml
  src/main/java/org/entando/kubernetes/client/DefaultEntandoResourceClient.java
  src/main/java/org/entando/kubernetes/client/DefaultIngressClient.java
  src/main/java/org/entando/kubernetes/client/PatchableClient.java
  src/main/java/org/entando/kubernetes/controller/AbstractDbAwareController.java
  src/main/java/org/entando/kubernetes/controller/k8sclient/EntandoResourceClient.java
  src/main/java/org/entando/kubernetes/controller/k8sclient/IngressClient.java
  src/test/java/org/entando/kubernetes/controller/common/examples/SampleController.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ControllerExecutorTestBase.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/DefaultClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/SpringBootContainerTestBase.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/k8sclientdouble/EntandoResourceClientDouble.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/k8sclientdouble/IngressClientDouble.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployEntandoDbConsumerTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployExampleServiceOnExternalDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployExampleServiceTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/AddExampleWithEmbeddedDatabaseIT.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/podwaiters/PodWaiterTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/support/IntegrationTestHelperBase.java
Labels: approved, size/L

#17 Fix finalizer removal
  src/test/java/org/entando/kubernetes/controller/integrationtest/AddExampleWithEmbeddedDatabaseIT.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/support/K8SIntegrationTestHelper.java
Labels: approved, size/M

#19 Reverted to 6.1.0
  config/checkstyle/checkstyle.xml
  config/intellij-java-entando-style.xml
  config/owasp-dependency-check-suppression.xml
  jenkins-x.yml
  pom.xml
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ContainerUsingExternalDatabaseMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ControllerExecutorMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ControllerExecutorMockServerTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/DefaultClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ImageResolutionTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/PublicIngressingMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/PublicIngressingMockServerTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/SpringBootContainerMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployEntandoDbConsumerTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployExampleServiceOnExternalDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployExampleServiceTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/AddExampleWithEmbeddedDatabaseIT.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/KeycloakClientIT.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/podwaiters/PodWaiterTest.java
Labels: approved, size/XXL

#22 Fixed tests
  jenkins-x.yml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/AbstractDbAwareController.java
  src/test/java/org/entando/kubernetes/controller/common/examples/MinimalKeycloakContainer.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ContainerUsingExternalDatabaseMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ControllerExecutorMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ControllerExecutorMockServerTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/DefaultClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/ImageResolutionTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/InProcessTestUtil.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/PublicIngressingMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/PublicIngressingMockServerTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/SpringBootContainerMockClientTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/SpringBootContainerTestBase.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployEntandoDbConsumerTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployExampleServiceOnExternalDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/inprocesstest/legacy/DeployExampleServiceTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/AddExampleWithEmbeddedDatabaseTest.java
  src/test/java/org/entando/kubernetes/controller/integrationtest/KeycloakClientTest.java
Labels: size/L
