Repository entando-k8s/entando-k8s-operator-common, pull requests merged in 2021-03, with the labels that each got.

#57 Eng 1876 deleted duplicate code
  README.md
  pom.xml
  src/main/java/org/entando/kubernetes/controller/spi/common/SecretUtils.java
  src/main/java/org/entando/kubernetes/controller/spi/container/SpringBootDeployableContainer.java
  src/main/java/org/entando/kubernetes/controller/spi/container/TrustStoreAware.java
  src/main/java/org/entando/kubernetes/controller/support/common/EntandoOperatorConfig.java
  src/main/java/org/entando/kubernetes/controller/support/common/EntandoOperatorConfigProperty.java
  src/main/java/org/entando/kubernetes/controller/support/common/TlsHelper.java
  src/main/java/org/entando/kubernetes/controller/support/controller/AbstractDbAwareController.java
  src/main/java/org/entando/kubernetes/controller/support/controller/ControllerExecutor.java
  src/main/java/org/entando/kubernetes/controller/support/controller/ControllerImageResolver.java
  src/main/java/org/entando/kubernetes/controller/support/controller/DefaultControllerImageResolver.java
  src/main/java/org/entando/kubernetes/controller/support/creators/DeploymentCreator.java
  src/main/java/org/entando/kubernetes/controller/support/creators/IngressCreator.java
  src/main/java/org/entando/kubernetes/controller/support/creators/SecretCreator.java
  src/test/java/org/entando/kubernetes/client/integrationtesthelpers/HttpTestHelper.java
  src/test/java/org/entando/kubernetes/client/integrationtesthelpers/TestFixturePreparation.java
  src/test/java/org/entando/kubernetes/controller/spi/examples/SampleDeployableContainer.java
  src/test/java/org/entando/kubernetes/controller/support/common/TlsHelperTest.java
  src/test/java/org/entando/kubernetes/test/common/CertificateSecretHelper.java
  src/test/java/org/entando/kubernetes/test/componenttest/ControllerExecutorTestBase.java
  src/test/java/org/entando/kubernetes/test/componenttest/SpringBootContainerTestBase.java
  src/test/java/org/entando/kubernetes/test/componenttest/legacy/DeployExampleServiceTest.java
  src/test/java/org/entando/kubernetes/test/e2etest/AddExampleWithContainerizedDatabaseTest.java
  src/test/java/org/entando/kubernetes/test/e2etest/common/ControllerContainerStartingListener.java
  src/test/java/org/entando/kubernetes/test/sandbox/serialization/SerializingDeployCommand.java
Labels: approved, size/XL

#58 Eng 2068 update ubi
  Dockerfile.jvm
  pom.xml
  src/main/java/org/entando/kubernetes/controller/support/common/EntandoOperatorConfig.java
  src/main/java/org/entando/kubernetes/controller/support/common/EntandoOperatorConfigProperty.java
  src/main/java/org/entando/kubernetes/controller/support/creators/PersistentVolumeClaimCreator.java
Labels: approved, size/S

#59 #ENG-2114 refined PVC logic with overridable storageClasses and accessmodes
  pom.xml
  src/main/java/org/entando/kubernetes/controller/spi/common/EntandoOperatorSpiConfig.java
  src/main/java/org/entando/kubernetes/controller/spi/common/EntandoOperatorSpiConfigProperty.java
  src/main/java/org/entando/kubernetes/controller/spi/container/PersistentVolumeAware.java
  src/main/java/org/entando/kubernetes/controller/spi/database/DatabaseContainer.java
  src/main/java/org/entando/kubernetes/controller/support/common/EntandoOperatorConfig.java
  src/main/java/org/entando/kubernetes/controller/support/common/EntandoOperatorConfigProperty.java
  src/main/java/org/entando/kubernetes/controller/support/creators/PersistentVolumeClaimCreator.java
Labels: approved, size/M
